export interface Candidate {
  key: string;
  name: string;
  jobTitle: string;
  industry: string;
  recentCompany: string;
  jobFunction: string;
  school: string;
  degree: string;
  experience: number;
  channels: readonly ('view' | 'phone' | 'mail' | 'linkedin' | 'wechat')[];
}

export const candidateData: readonly Candidate[] = [
  {
    key: 'yang',
    name: '杨女士',
    jobTitle: '招聘运营专家',
    industry: '互联网服务',
    recentCompany: '云帆科技',
    jobFunction: 'Talent Acquisition',
    school: '湖北大学',
    degree: 'Bachelor',
    experience: 8,
    channels: ['view', 'mail'],
  },
  {
    key: 'stacey',
    name: 'Stacey Anderson',
    jobTitle: 'Senior Recruiting Manager',
    industry: 'Professional Services',
    recentCompany: 'Arena Family of Companies',
    jobFunction: 'Human Resources',
    school: 'San Diego State University',
    degree: 'MBA',
    experience: 12,
    channels: ['view', 'mail', 'linkedin'],
  },
  {
    key: 'liu',
    name: '刘思姣',
    jobTitle: 'OD 专家 / SSC 负责人',
    industry: 'Artificial Intelligence',
    recentCompany: '人工智能实验室',
    jobFunction: 'Talent & Organization',
    school: '上海财经大学',
    degree: 'Master',
    experience: 10,
    channels: ['phone', 'mail'],
  },
  {
    key: 'wan',
    name: '万颖樱',
    jobTitle: 'COE 人才发展与干部管理',
    industry: 'Pharmaceutical',
    recentCompany: '上海药明康德',
    jobFunction: 'Talent Development',
    school: '复旦大学',
    degree: 'Master',
    experience: 9,
    channels: ['view', 'phone', 'mail'],
  },
  {
    key: 'qian',
    name: '钱康屹',
    jobTitle: '市场营销负责人',
    industry: 'Intelligent Hardware',
    recentCompany: '奇点临近技术',
    jobFunction: 'Marketing Planning',
    school: '上海第二工业大学',
    degree: 'Bachelor',
    experience: 7,
    channels: ['view', 'phone', 'mail', 'wechat'],
  },
  {
    key: 'zhou',
    name: '周筱乐',
    jobTitle: '全球人力资源 COE 及 SSC',
    industry: 'Web / APP Product',
    recentCompany: 'Bitunix',
    jobFunction: 'Human Resources',
    school: '北京邮电大学',
    degree: 'Master',
    experience: 11,
    channels: ['view', 'phone', 'mail'],
  },
  {
    key: 'meng',
    name: '蒙先生',
    jobTitle: '环境、健康与安全管理',
    industry: 'Automation Equipment',
    recentCompany: '歌尔股份',
    jobFunction: 'Safety Management',
    school: '云南农业大学',
    degree: 'Bachelor',
    experience: 13,
    channels: ['view', 'phone', 'mail'],
  },
  {
    key: 'sun',
    name: '孙宇',
    jobTitle: '增长活跃度方向',
    industry: 'Web / APP Product',
    recentCompany: '某头部互联网公司',
    jobFunction: 'User Operation',
    school: '中国科学技术大学',
    degree: 'Master',
    experience: 6,
    channels: ['view', 'phone', 'mail'],
  },
  {
    key: 'qiu',
    name: '邱先生',
    jobTitle: '驻外销售管理 / 产品管理',
    industry: 'Intelligent Household Electronics',
    recentCompany: '宁波奥克斯',
    jobFunction: 'Sales Operations',
    school: '河南理工大学',
    degree: 'Bachelor',
    experience: 9,
    channels: ['phone', 'mail'],
  },
  {
    key: 'chen',
    name: '陈婧',
    jobTitle: 'HR Business Partner',
    industry: 'Robotics',
    recentCompany: '具身智能研究院',
    jobFunction: 'HRBP',
    school: '华东师范大学',
    degree: 'Master',
    experience: 8,
    channels: ['view', 'mail', 'linkedin'],
  },
  {
    key: 'alex',
    name: 'Alex Morgan',
    jobTitle: 'Recruitment Operations Lead',
    industry: 'FinTech',
    recentCompany: 'Northstar Capital',
    jobFunction: 'Recruiting Operations',
    school: 'University of Toronto',
    degree: 'Bachelor',
    experience: 10,
    channels: ['view', 'mail', 'linkedin'],
  },
  {
    key: 'lin',
    name: '林若溪',
    jobTitle: '组织发展高级经理',
    industry: 'New Energy',
    recentCompany: '远景能源',
    jobFunction: 'Organization Development',
    school: '南京大学',
    degree: 'Master',
    experience: 12,
    channels: ['view', 'phone', 'mail'],
  },
];
